import Nav from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="dark text-foreground bg-background ">
          <Nav />
          <div className="w-screen h-screen flex items-start justify-center px-40 py-10 m-0">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
